---
- name: "Deploy CNV"
  hosts: localhost
  roles:
    - deploy_cnv

- name: "Ping cnv nodes"
  hosts: cnv
  tasks:
    - name: "Ping node"
      debug:
        msg: "test"

- name: "Test common templates"
  hosts: localhost
  tasks:
    - name: "Retrieve common templates"
      k8s_facts:
        kind: Template
        namespace: openshift
        label_selectors:
          - template.cnv.io/type = base
      register: templates

    - set_fact:
        oses: "{{ templates.resources
                    |map(attribute='metadata.labels')
                    |keys
                    |flatten
                    |select('match', '^os.template.cnv.io/.*')
                    |countitems }}"
                    

    - name: "Check presence of all required OSes"
      assert:
        that:
          - "oses['os.template.cnv.io/centos7.0'] > 0"

    - name: "Instantiate template"
      include_role:
        name: oc_post_template
      vars:
        namespace: myproject
        template: "{{ item }}"
        parameters:
          PVCNAME: test-dummy-pvc
        cleanup: true
      with_items: "{{ templates.resources }}"

