---
- name: "Deploy CNV"
  hosts: localhost
  roles:
    - deploy_cnv

- name: "Run a VM"
  hosts: localhost
  vars_files:
    - fixtures/defaults.yml
  vars:
    vm_cpus: 1
    vm_memory_size: 512Mi
  tasks:
  - block:
    - name: "Define a VM"
      k8s:
        state: present
        namespace: myproject
        definition: "{{ lookup('template', 'fixtures/vm-cirros.yaml') }}"
      register: vm

    - debug: msg={{ vm }}

    - name: "Start a VM"
      k8s:
        state: present
        kind: "{{ vm.result.kind }}"
        namespace: "{{ vm.result.metadata.namespace }}"
        api_version: "{{ vm.result.apiVersion }}"
        name: "{{ vm.result.metadata.name }}"
        definition:
          spec:
            running: true

    - name: "Wait for the VM to start"
      k8s_facts:
        kind: "{{ vm.result.kind }}"
        namespace: "{{ vm.result.metadata.namespace }}"
        api_version: "{{ vm.result.apiVersion }}"
        name: "{{ vm.result.metadata.name }}"
      register: vm_status
      retries: 60
      delay: 10
      until: vm_status.resources[0].status.ready|default(false)

    - name: "Wait for the VMI to get IP"
      k8s_facts:
        kind: "VirtualMachineInstance"
        namespace: "{{ vm.result.metadata.namespace }}"
        api_version: "{{ vm.result.apiVersion }}"
        name: "{{ vm.result.metadata.name }}"
      register: vmi_status
      retries: 60
      delay: 10
      until: vmi_status.resources[0].status.interfaces[0].ipAddress|default("") != ""

    - set_fact:
        "vm_{{ vm.result.metadata.name|varname }}_ip": "{{ vmi_status.resources[0].status.interfaces[0].ipAddress }}"

    - meta: refresh_inventory

    - pause:

    - name: "Stop a VM"
      k8s:
        state: present
        kind: "{{ vm.result.kind }}"
        namespace: "{{ vm.result.metadata.namespace }}"
        api_version: "{{ vm.result.apiVersion }}"
        name: "{{ vm.result.metadata.name }}"
        definition:
          spec:
            running: false

    - name: "Wait for the VM to stop"
      k8s_facts:
        kind: "{{ vm.result.kind }}"
        namespace: "{{ vm.result.metadata.namespace }}"
        api_version: "{{ vm.result.apiVersion }}"
        name: "{{ vm.result.metadata.name }}"
      register: vm_status
      retries: 60
      delay: 10
      until: vm_status.resources[0].status.ready|default(false) == false

    always:
    - name: "Remove a VM"
      k8s:
        state: absent
        definition: "{{ vm.result }}"

